### ISSUE TITLE
My install packages keeps crashing pls help

### ISSUE THREAD

**Issue by Olivertron69ondisc** [LunarFN/AutoHost#1]
My install packages keeps crashing pls help😭
I have no idea why (I have node js)

**Comment by secret-pommes** [comment]
install VCBuild Tools & python

**Comment by Olivertron69ondisc** [comment]
![asdasd](https://github.com/user-attachments/assets/68b920b3-ada4-43c7-a503-5f677c274960)
idk if the pic worked but that keeps happening

**Comment by Olivertron69ondisc** [comment]
and also i cant download pyhton

**Comment by secret-pommes** [comment]
did you selected C++ development in VSTools?

**Comment by Olivertron69ondisc** [comment]
yeah i have this one 
![image](https://github.com/user-attachments/assets/bb5009f7-f5c8-499a-93d3-a834762726e1)

**Comment by Olivertron69ondisc** [comment]
and im downloading the other one rn to test that out

**Comment by Olivertron69ondisc** [comment]
nah still dont work even with this installed
![image](https://github.com/user-attachments/assets/11bd10f1-c379-44ec-9e37-17251f5bf989)
